from Taylor import LhsScenario
from default_case import DEFAULT_SEED


def build_edge_case_scenarios() -> list[tuple[str, LhsScenario]]:
    """
    Define explicit edge case scenarios for testing.
    Returns a list of tuples (case_name, scenario).

    NOTE: The ROI and CPI behavior for each edge case depends on scenario fields
    and downstream model settings.
    """
    return [
        (
            "EC_0_0",
            LhsScenario(
                man_age_to_al=69.0 + 0,
                woman_age_to_al=70.29 + 0,
                man_linger=0.0,
                woman_linger=0.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_0_5",
            LhsScenario(
                man_age_to_al=69.0 + 0,
                woman_age_to_al=70.29 + 0,
                man_linger=5.0,
                woman_linger=5.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_0_10",
            LhsScenario(
                man_age_to_al=69.0 + 0,
                woman_age_to_al=70.29 + 0,
                man_linger=10.0,
                woman_linger=10.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_0_15",
            LhsScenario(
                man_age_to_al=69.0 + 0,
                woman_age_to_al=70.29 + 0,
                man_linger=15.0,
                woman_linger=15.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_5_0",
            LhsScenario(
                man_age_to_al=69.0 + 5,
                woman_age_to_al=70.29 + 5,
                man_linger=0.0,
                woman_linger=0.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_5_5",
            LhsScenario(
                man_age_to_al=69.0 + 5,
                woman_age_to_al=70.29 + 5,
                man_linger=5.0,
                woman_linger=5.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_5_10",
            LhsScenario(
                man_age_to_al=69.0 + 5,
                woman_age_to_al=70.29 + 5,
                man_linger=10.0,
                woman_linger=10.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_5_15",
            LhsScenario(
                man_age_to_al=69.0 + 5,
                woman_age_to_al=70.29 + 5,
                man_linger=15.0,
                woman_linger=15.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_10_0",
            LhsScenario(
                man_age_to_al=69.0 + 10,
                woman_age_to_al=70.29 + 10,
                man_linger=0.0,
                woman_linger=0.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_10_5",
            LhsScenario(
                man_age_to_al=69.0 + 10,
                woman_age_to_al=70.29 + 10,
                man_linger=5.0,
                woman_linger=5.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_10_10",
            LhsScenario(
                man_age_to_al=69.0 + 10,
                woman_age_to_al=70.29 + 10,
                man_linger=10.0,
                woman_linger=10.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_10_15",
            LhsScenario(
                man_age_to_al=69.0 + 10,
                woman_age_to_al=70.29 + 10,
                man_linger=15.0,
                woman_linger=15.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_15_0",
            LhsScenario(
                man_age_to_al=69.0 + 15,
                woman_age_to_al=70.29 + 15,
                man_linger=0.0,
                woman_linger=0.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_15_5",
            LhsScenario(
                man_age_to_al=69.0 + 15,
                woman_age_to_al=70.29 + 15,
                man_linger=5.0,
                woman_linger=5.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_15_10",
            LhsScenario(
                man_age_to_al=69.0 + 15,
                woman_age_to_al=70.29 + 15,
                man_linger=10.0,
                woman_linger=10.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_15_15",
            LhsScenario(
                man_age_to_al=69.0 + 15,
                woman_age_to_al=70.29 + 15,
                man_linger=15.0,
                woman_linger=15.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.01,
                roi_vol_multiplier=0.5,
                roi_mean_reversion=0.5,
                inflation_mean_shift=-0.005,
                inflation_vol_multiplier=0.5,
                inflation_mean_reversion=0.5,
            ),
        ),
        (
            "EC_85_1",
            LhsScenario(
                man_age_to_al=85.0,
                woman_age_to_al=85.0,
                man_linger=1.0,
                woman_linger=1.0,
                roi_seed=DEFAULT_SEED,
                inflation_seed=DEFAULT_SEED,
                roi_mean_shift=0.005,
                roi_vol_multiplier=1.2,
                roi_mean_reversion=0.15,
                inflation_mean_shift=0.002,
                inflation_vol_multiplier=1.1,
                inflation_mean_reversion=0.15,
            ),
        ),
    ]

